local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0  # decreased because "Map update missed its desired rate
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05
  transform_tolerance: 0.3 # decreased because "Control loop missed its desired rate
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
